name: Node.js CI

on:
  push:
    branches: [ main, evento]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: 16.13.0
    - run: npm install
    - run: npm run build --if-present
    - run: npm test-mocked
